# local
server:
  port: 8000

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ENC(DRHELuiVgs9T+6S6D4ugFdPNwAfsVRUuXPw5I7fN42ZsxDjT5bpQ3qclpbJm1yFX)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Qq07MPccudPTux6ZD6Womw==)
    password: ENC(Y+SSOYUaJat/NqxuNvbRYxljnnxNyaBn)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 1000
      hibernate:
        format_sql: true
    #    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    credential:
      accessKey: ENC(w9ds6I7mo/cjg8mG+FIv0aW3C/Jr/fie8zik1pRmtdQ=)
      secretKey: ENC(UDgthukdmkkXBC2Bznpfp/1cvht/LucBVuMs27XnLWBW1vJ8OE4O0vHGTz+r3Oqs6jxlop0dHmw=)

    s3:
      region: ap-northeast-2
      bucket: xcape-business-sdk-uploads-dev
      json:
        path: json/
      origin-endpoint: ENC(XduLH5YfFldnGiCdsDxReYusC9cDYgtuB0YKTeZrsGLhJpaMBPzhUSk16fsr5vRmQUl+P51fVekC+B8uqKrsWYLY1gFdQ34PjK9IQJOvd0M=)
      cloud-front-endpoint: ENC(RNDeTk90JhA8KZiHFRykchS583TzjUU7+hO4g949KI+CrjSrEvfrYsR4rgS2oWs6)


kakao:
  host: https://api-alimtalk.cloud.toast.com
  senderKey: ENC(Uz5eKsiJjt+Ci68GruukDvUo//FjviaxmBBJsdgolLMZsWhKyWpZI4SSxctEaKnbz/TmB59Z9RA=)
  secretKey: ENC(vrsnnwSRWVVq0mDqmdakvv1vKmFGmzIA)
  appKey: ENC(uTaPfgQJ/uoDlagTSbWSGfGRmcZ+teA6Ap7hQaCXaxg=)
  templateCode:
    authenticate: xcape-authenticate

sms:
  sendNo: 01093736081
  host: https://api-sms.cloud.toast.com
  secretKey: ENC(erqLmX533rM+812LB2NPAoHQQ3Z5BWu3)
  appKey: ENC(dukcgC1Gns2PGtnOvgx/7XVgVUz4pTLL+1a99ZxeL2E=)

firebase:
  storage:
    config-file: classpath:serviceAccountKeyDev.json
    bucket: ENC(K4nrWxeJXLPHNNp1ytv9734teeMcknH5UpHAfLxSqTs=)
    prefix: ENC(HMlHXm+9ft0WBUKKFrMmAnC2qqavZQdeps0+2+yInEQNZD6JgC+tqYoOF2+WfKI4B7b/ixBvuUwkrJlZFGuAD349OV4Afpol2eJF/9Zdf54=)
