spring:
  profiles:
    active: local

cloud:
  aws:
    credential:
      accessKey: ENC(w9ds6I7mo/cjg8mG+FIv0aW3C/Jr/fie8zik1pRmtdQ=)
      secretKey: ENC(UDgthukdmkkXBC2Bznpfp/1cvht/LucBVuMs27XnLWBW1vJ8OE4O0vHGTz+r3Oqs6jxlop0dHmw=)

    s3:
      region: ap-northeast-2
      bucket: xcape-business-sdk-uploads
      json:
        path: json/
      origin-endpoint: ENC(XduLH5YfFldnGiCdsDxReYusC9cDYgtuB0YKTeZrsGLhJpaMBPzhUSk16fsr5vRmQUl+P51fVekC+B8uqKrsWYLY1gFdQ34PjK9IQJOvd0M=)
      cloud-front-endpoint: ENC(RNDeTk90JhA8KZiHFRykchS583TzjUU7+hO4g949KI+CrjSrEvfrYsR4rgS2oWs6)

---
spring:
  datasource:
    url: ENC(DRHELuiVgs9T+6S6D4ugFdPNwAfsVRUuXPw5I7fN42ZsxDjT5bpQ3qclpbJm1yFX)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Qq07MPccudPTux6ZD6Womw==)
    password: ENC(Y+SSOYUaJat/NqxuNvbRYxljnnxNyaBn)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 1000
      hibernate:
        format_sql: true
#    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    activate:
      on-profile: local

cloud:
  aws:
    s3:
      region: ap-northeast-2
      bucket: xcape-business-sdk-uploads-dev
      json:
        path: json/

server:
  port: 8000

kakao:
  host: https://api-alimtalk.cloud.toast.com
  senderKey: ENC(Uz5eKsiJjt+Ci68GruukDvUo//FjviaxmBBJsdgolLMZsWhKyWpZI4SSxctEaKnbz/TmB59Z9RA=)
  secretKey: ENC(vrsnnwSRWVVq0mDqmdakvv1vKmFGmzIA)
  appKey: ENC(uTaPfgQJ/uoDlagTSbWSGfGRmcZ+teA6Ap7hQaCXaxg=)
  templateCode:
    authenticate: xcape-authenticate

sms:
  sendNo: 01093736081
  host: https://api-sms.cloud.toast.com
  secretKey: ENC(erqLmX533rM+812LB2NPAoHQQ3Z5BWu3)
  appKey: ENC(dukcgC1Gns2PGtnOvgx/7XVgVUz4pTLL+1a99ZxeL2E=)

firebase:
  storage:
    config-file: classpath:serviceAccountKeyDev.json
    bucket: ENC(K4nrWxeJXLPHNNp1ytv9734teeMcknH5UpHAfLxSqTs=)
    prefix: ENC(HMlHXm+9ft0WBUKKFrMmAnC2qqavZQdeps0+2+yInEQNZD6JgC+tqYoOF2+WfKI4B7b/ixBvuUwkrJlZFGuAD349OV4Afpol2eJF/9Zdf54=)

---
spring:
  datasource:
    url: jdbc:mysql://xcape-business-sdk-dev.c8xnc6bsoj2c.ap-northeast-2.rds.amazonaws.com/xcape
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Prx5zMshXO3p3XFnEa9/SlBuxtOsp7GI)
    password: ENC(kJnH9OX8imK2yOykyWWzAT3LdlbDEjE+)
    hikari:
      max-lifetime: 58000
      maximum-pool-size: 25
#      connection pool sizing:
#         thread count: 10
#         simultaneous connection count: 3(jpa - 2, scheduling - 1)
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 50MB
  task:
    scheduling:
      pool:
        size: 4
      thread-name-prefix: scheduling-

kakao:
  host: https://api-alimtalk.cloud.toast.com
  senderKey: ENC(Uz5eKsiJjt+Ci68GruukDvUo//FjviaxmBBJsdgolLMZsWhKyWpZI4SSxctEaKnbz/TmB59Z9RA=)
  secretKey: ENC(vrsnnwSRWVVq0mDqmdakvv1vKmFGmzIA)
  appKey: ENC(uTaPfgQJ/uoDlagTSbWSGfGRmcZ+teA6Ap7hQaCXaxg=)
  templateCode:
    authenticate: xcape-authenticate

sms:
  sendNo: 01093736081
  host: https://api-sms.cloud.toast.com
  secretKey: ENC(erqLmX533rM+812LB2NPAoHQQ3Z5BWu3)
  appKey: ENC(dukcgC1Gns2PGtnOvgx/7XVgVUz4pTLL+1a99ZxeL2E=)

cloud:
  aws:
    s3:
      region: ap-northeast-2
      bucket: xcape-business-sdk-uploads
      json:
        path: json/

server:
  port: 5000

firebase:
  storage:
    config-file: classpath:serviceAccountKeyProd.json
    bucket: ENC(7yH4kHTK1AU2Zm+ZNsZMismuFos7yhsKMYsb5dTq3P67tOWGtVYmjg==)
    prefix: ENC(l/fgFbGcNxF6vZ16V5MnQDr26thg0swd0BuBB1paENH/mFCOUBNQkFN5xkKrZWMMMoMiQ54055iASpOuXlwg2lUgAuzfIcvMqSqFIYkN2eHt4kIRWhxi/A==)
